global:
  resolve_timeout: 5m

route:
  group_by: ["alertname"] #Nhóm cảnh báo theo tên cảnh báo
  group_wait: 30s # Thời gian chờ trước khi gửi nhóm cảnh báo đầu tiên
  group_interval: 5m # Thời gian chờ giữa các lần gửi nhóm cảnh báo tiếp theo nếu vẫn còn cảnh báo chưa được giải quyết
  repeat_interval: 3h # Thời gian chờ trước khi gửi lại cảnh báo đã được gửi trước đó nếu vẫn chưa được giải quyết
  receiver: "slack" #

receivers:
  - name: "slack"
    slack_configs:
      - channel: "#monitoring_project_slack"
        api_url: "${SLACK_WEB_HOOK_URL}"
        send_resolved: true # Gửi thông báo khi cảnh báo được giải quyết
