services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    networks:
      - ecom-network

  backend:
    build: ./02-backend_spring-boot-rest-api
    container_name: backend-springboot
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - ecom-network

  frontend:
    build: ./03-frontend_angular-ecommerce
    container_name: frontend-angular
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ecom-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - ecom-network

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - ecom-network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./monitoring/loki/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - ecom-network
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alerts/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus-data:/prometheus
    depends_on:
      - backend
      - alertmanager
    networks:
      - ecom-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - ecom-network
    depends_on:
      - prometheus

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alerts/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - ecom-network
    restart: always

networks:
  ecom-network:
    driver: bridge
volumes:
  grafana-data:
  prometheus-data:
