{
 "title": "HTTP Requests per Second",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Application Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Requests Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count[1m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "System Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    { "expr": "process_cpu_usage * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Application Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds", "legendFormat": "__auto" }
   ]
  }
 ]
}